version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "emails-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-8ebikdn4robt"
s3_prefix = "emails-api"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
